spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icet_crm
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
